### ISSUE TITLE
nodeless.js is not completely replaced by grunt task

### ISSUE THREAD

**Issue by matthijsln** [opengeogroep/safetymapsDBK#21]
- config.json nodeless:deploy dir copy for customer customization not copied to output (feature also needed for dynamic node version)
- non-minified version for debugging missing
- fast development option missing (nodeless_fast.sh, skip generating api/ files)
- perhaps other differences

Will continue to use nodeless.js and bash scripts for mobile/fullscreen versions for now.

**Comment by milovanderlinden** [comment]
This issue was moved to dogodigi/opendispatcher#443
